
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author USER
 */
public class FinalizarTrabajo extends javax.swing.JFrame {
    int vc=0;
    /**
     * Creates new form FinalizarTrabajo
     */
    public FinalizarTrabajo() {
        initComponents();
        this.setLocationRelativeTo(this);
        
        //fondo
        ImageIcon imagen = new ImageIcon(getClass().getResource("/fondos/faumentos.jpg"));
        Icon fondo = new ImageIcon(imagen.getImage().getScaledInstance(Lfondo.getWidth(), Lfondo.getHeight(), Image.SCALE_DEFAULT));
        Lfondo.setIcon(fondo);
        this.repaint();
        
        //Tabla Todos
        DefaultTableModel modelo = (DefaultTableModel) Ttrabajosactivos.getModel();
        modelo.getDataVector().clear();
        //creamos filas en la table si hay trabajos en proceso
        for (int k = 0; k < registro.trabajos.size(); k++) {
            if(registro.trabajos.get(k).getEstado()==false){
                vc++;
                modelo.addRow(new Object[]{"", "", "", "", ""});
            }
        }
        
        //si no hay trabajos en proceso, mostramos el mensaje
        if(vc==0){
            JOptionPane.showMessageDialog(this, "No hay trabajos en proceso");
            
        //sino mostramos mostramos los trabajos en proceso    
        }else{
            vc=0;
            for (int i = 0; i < registro.trabajos.size(); i++) {
                if(registro.trabajos.get(i).getEstado()==false){
                    Ttrabajosactivos.setValueAt(registro.trabajos.get(i).getId(), vc, 0);
                    Ttrabajosactivos.setValueAt(registro.trabajos.get(i).getTipotrabajo(), vc, 1);
                    Ttrabajosactivos.setValueAt(registro.trabajos.get(i).getDescripcion(), vc, 2);
                    Ttrabajosactivos.setValueAt(registro.trabajos.get(i).getNhoras(), vc, 3);
                    if(registro.trabajos.get(i).getEstado()==false){
                        Ttrabajosactivos.setValueAt("En proceso", vc, 4);
                    }else{
                        Ttrabajosactivos.setValueAt("Finalizado", vc, 4);
                    }
                    vc++;
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Ttrabajosactivos = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        TFidtrabajo = new javax.swing.JTextField();
        Bfinalizar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Lfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Ttrabajosactivos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Ttrabajosactivos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "TRABAJO", "DESCRIPCIÓN", "HORAS", "ESTADO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(Ttrabajosactivos);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 40, 470, 170));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ingrese ID del trabajo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        TFidtrabajo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TFidtrabajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFidtrabajoActionPerformed(evt);
            }
        });

        Bfinalizar.setBackground(new java.awt.Color(255, 0, 0));
        Bfinalizar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Bfinalizar.setText("Finalizar");
        Bfinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BfinalizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TFidtrabajo, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(Bfinalizar, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Bfinalizar, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(TFidtrabajo))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 400, 170));

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 441, 130, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("FINALIZAR TRABAJOS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));
        jPanel1.add(Lfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TFidtrabajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFidtrabajoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFidtrabajoActionPerformed

    private void BfinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BfinalizarActionPerformed
        // TODO add your handling code here:
        boolean valid=false;
        int pos=0;
        if(TFidtrabajo.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Debe ingresar una ID", "ERROR", JOptionPane.WARNING_MESSAGE);
        }else{
            //buscamos el ID
            for (int i = 0; i < registro.trabajos.size(); i++) {
                if(registro.trabajos.get(i).getEstado()==false){
                    if(registro.trabajos.get(i).getId().equalsIgnoreCase(TFidtrabajo.getText())){
                        valid=true;
                        pos=i;
                    }
                }
            }
            
            //validamos si lo encontró
            if(valid){
                int vc=0;
                registro.trabajos.get(pos).changeEstado();
                JOptionPane.showMessageDialog(this, "Estado cambiado con exito a trabajo con ID: "+registro.trabajos.get(pos).getId());
                
                //Actualizamos la tabla
                DefaultTableModel modelo = (DefaultTableModel) Ttrabajosactivos.getModel();
                modelo.getDataVector().clear();
                //creamos filas en la table si hay trabajos en proceso
                for (int k = 0; k < registro.trabajos.size(); k++) {
                    if(registro.trabajos.get(k).getEstado()==false){
                        modelo.addRow(new Object[]{"", "", "", "", ""});
                    }
                }
                for (int i = 0; i < registro.trabajos.size(); i++) {
                    if(registro.trabajos.get(i).getEstado()==false){
                        System.out.println(vc);
                        Ttrabajosactivos.setValueAt(registro.trabajos.get(i).getId(), vc, 0);
                        Ttrabajosactivos.setValueAt(registro.trabajos.get(i).getTipotrabajo(), vc, 1);
                        Ttrabajosactivos.setValueAt(registro.trabajos.get(i).getDescripcion(), vc, 2);
                        Ttrabajosactivos.setValueAt(registro.trabajos.get(i).getNhoras(), vc, 3);
                        if(registro.trabajos.get(i).getEstado()==false){
                            Ttrabajosactivos.setValueAt("En proceso", vc, 4);
                        }else{
                            Ttrabajosactivos.setValueAt("Finalizado", vc, 4);
                        }
                        vc++;
                    }
                }
                    
            }else{
                JOptionPane.showMessageDialog(this, "ID no encontrada");
            }
        }

        

    }//GEN-LAST:event_BfinalizarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FinalizarTrabajo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FinalizarTrabajo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FinalizarTrabajo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FinalizarTrabajo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FinalizarTrabajo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bfinalizar;
    private javax.swing.JLabel Lfondo;
    private javax.swing.JTextField TFidtrabajo;
    private javax.swing.JTable Ttrabajosactivos;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
