import java.awt.Image;
import java.util.ArrayList;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;


/**
 *
 * @author USER
 */
public class registro extends javax.swing.JFrame {
    public static ArrayList <Reparacion> reparaciones = new ArrayList();
    public static ArrayList <Revision> revisiones = new ArrayList();
    public static ArrayList <Trabajo> trabajos = new ArrayList();
    static int idrep=1, idrev=1;
    /**
     * Creates new form registro2
     */
    public registro() {
        initComponents();
        this.setLocationRelativeTo(this);
        
        //Desactivamos
        RBlatoneria.setEnabled(false);
        RBmecanica.setEnabled(false);
        
        //fondo
        ImageIcon imagen = new ImageIcon(getClass().getResource("/fondos/fondoagregar.jpg"));
        Icon fondo = new ImageIcon(imagen.getImage().getScaledInstance(Lfondo.getWidth(), Lfondo.getHeight(), Image.SCALE_DEFAULT));
        Lfondo.setIcon(fondo);
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        RBmecanica = new javax.swing.JRadioButton();
        RBlatoneria = new javax.swing.JRadioButton();
        RBreparacion = new javax.swing.JRadioButton();
        jPanel6 = new javax.swing.JPanel();
        RBdiagnostico = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        TFdescripcion = new javax.swing.JTextField();
        Bguardar = new javax.swing.JButton();
        Bsalir = new javax.swing.JButton();
        Lfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("REGISTRO DE TRABAJO");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("TIPO DE TRABAJO ");

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        buttonGroup2.add(RBmecanica);
        RBmecanica.setText("Mécanica");

        buttonGroup2.add(RBlatoneria);
        RBlatoneria.setText("Latonería y Pintura");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RBmecanica)
                    .addComponent(RBlatoneria))
                .addGap(0, 28, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(RBmecanica)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RBlatoneria)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        buttonGroup1.add(RBreparacion);
        RBreparacion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        RBreparacion.setText("Reparación");
        RBreparacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBreparacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RBreparacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(RBreparacion)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        buttonGroup1.add(RBdiagnostico);
        RBdiagnostico.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        RBdiagnostico.setText("Diagnostico");
        RBdiagnostico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBdiagnosticoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RBdiagnostico)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(RBdiagnostico)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(168, 168, 168))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(33, 33, 33)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 40, 500, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("DESCRIPCION DEL TRABAJO");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(158, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(130, 130, 130))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TFdescripcion)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TFdescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        Bguardar.setBackground(new java.awt.Color(0, 0, 204));
        Bguardar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Bguardar.setText("guardar");
        Bguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BguardarActionPerformed(evt);
            }
        });
        jPanel1.add(Bguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, -1, -1));

        Bsalir.setBackground(new java.awt.Color(255, 0, 0));
        Bsalir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Bsalir.setText("Salir");
        Bsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BsalirActionPerformed(evt);
            }
        });
        jPanel1.add(Bsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 380, 90, -1));
        jPanel1.add(Lfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 440));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RBreparacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBreparacionActionPerformed
        // TODO add your handling code here:
        if(RBreparacion.isSelected()){
            RBlatoneria.setEnabled(true);
            RBmecanica.setEnabled(true);
        }
    }//GEN-LAST:event_RBreparacionActionPerformed

    private void RBdiagnosticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBdiagnosticoActionPerformed
        // TODO add your handling code here:
        if(RBdiagnostico.isSelected()){
            RBlatoneria.setEnabled(false);
            RBmecanica.setEnabled(false);
        }
    }//GEN-LAST:event_RBdiagnosticoActionPerformed

    private void BguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BguardarActionPerformed
        // TODO add your handling code here:
        boolean valrb=false, valdesc = false;
        

        //validamos selección de radiobuttons
        if(RBreparacion.isSelected()){
            if(RBmecanica.isSelected()){
                valrb=true;
            }else if(RBlatoneria.isSelected()){
                valrb=true;
            }
        }else if(RBdiagnostico.isSelected()){
            valrb=true;
        }

        //validamos el llenado de la descripción
        if(TFdescripcion.getText().equals("")){
            valdesc=false;
        }else{
            valdesc=true;
        }

        //Mostramos mensajes de validación de llenado
        if(valrb == true && valdesc ==true){ //Todos los datos llenos, guardamos el trabajo
            //Guardamos
            if(RBreparacion.isSelected()){
                if(RBmecanica.isSelected()){
                    Reparacion rep = new Reparacion("Mecánica","B"+idrep, TFdescripcion.getText(), "Reparación");
                    rep.setPrecio();
                    reparaciones.add(rep);
                    trabajos.add(rep);
                    idrep++;
                    JOptionPane.showMessageDialog(this, "Trabajo Agregado Exitosamente");
                }else if(RBlatoneria.isSelected()){
                    Reparacion rep = new Reparacion("Latonería y Pintura","B"+idrep, TFdescripcion.getText(), "Reparación");
                    rep.setPrecio();
                    reparaciones.add(rep);
                    trabajos.add(rep);
                    idrep++;
                    JOptionPane.showMessageDialog(this, "Trabajo Agregado Exitosamente");
                }
            }else if(RBdiagnostico.isSelected()){
                Revision rev = new Revision("A"+idrev, TFdescripcion.getText(), "Revisión");
                rev.setPrecio();
                revisiones.add(rev);
                trabajos.add(rev);
                idrev++;
                JOptionPane.showMessageDialog(this, "Trabajo Agregado Exitosamente");
            }
            //Limpiamos todas las selecciones
            TFdescripcion.setText("");
            buttonGroup1.clearSelection();
            buttonGroup2.clearSelection();
            RBlatoneria.setEnabled(false);
            RBmecanica.setEnabled(false);
        }else if(valrb == true && valdesc == false){ //Descripción vacía
            JOptionPane.showMessageDialog(this, "Debe escribir una descipción", "ERROR", JOptionPane.WARNING_MESSAGE);

        }else if(valrb == false && valdesc == true){ //Tipo de trabajo vacío
            JOptionPane.showMessageDialog(this, "Debe seleccionar un tipo de trabajo", "ERROR", JOptionPane.WARNING_MESSAGE);

        }else{ //Todo vacío
            JOptionPane.showMessageDialog(this, "Debe llenar todos los datos de registro", "ERROR", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_BguardarActionPerformed

    private void BsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BsalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_BsalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bguardar;
    private javax.swing.JButton Bsalir;
    private javax.swing.JLabel Lfondo;
    private javax.swing.JRadioButton RBdiagnostico;
    private javax.swing.JRadioButton RBlatoneria;
    private javax.swing.JRadioButton RBmecanica;
    private javax.swing.JRadioButton RBreparacion;
    private javax.swing.JTextField TFdescripcion;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    // End of variables declaration//GEN-END:variables
}
