
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author josee
 */
public class respuestos extends javax.swing.JFrame {
    int vc=0;
    /**
     * Creates new form respuestos
     */
    public respuestos() {
        initComponents();
        this.setLocationRelativeTo(this);
        
        //fondo
        ImageIcon imagen = new ImageIcon(getClass().getResource("/fondos/faumentos.jpg"));
        Icon fondo = new ImageIcon(imagen.getImage().getScaledInstance(Lfondo.getWidth(), Lfondo.getHeight(), Image.SCALE_DEFAULT));
        Lfondo.setIcon(fondo);
        this.repaint();
        
        //Tabla Todos
        DefaultTableModel modelo = (DefaultTableModel) Ttodos.getModel();
        modelo.getDataVector().clear();
        //creamos filas en la table si hay trabajos en proceso
        for (int k = 0; k < registro.reparaciones.size(); k++) {
            if(registro.reparaciones.get(k).getEstado()==false){
                modelo.addRow(new Object[]{"", "", "", "", ""});
                vc++;
            }
        }
        
        if(vc==0){
            JOptionPane.showMessageDialog(this, "No hay reparaciones en proceso");
            
        //sino mostramos mostramos los trabajos en proceso    
        }else{
            vc=0;
            for (int i = 0; i < registro.reparaciones.size(); i++) {
                if(registro.reparaciones.get(i).getEstado()==false){
                    Ttodos.setValueAt(registro.reparaciones.get(i).getId(), vc, 0);
                    Ttodos.setValueAt(registro.reparaciones.get(i).getTipotrabajo(), vc, 1);
                    Ttodos.setValueAt(registro.reparaciones.get(i).getDescripcion(), vc, 2);
                    Ttodos.setValueAt(registro.reparaciones.get(i).getPreciomaterial(), vc, 3);
                    if(registro.reparaciones.get(i).getEstado()==false){
                        Ttodos.setValueAt("En proceso", vc, 4);
                    }else{
                        Ttodos.setValueAt("Finalizado", vc, 4);
                    }
                    vc++;
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Ttodos = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        Bañadirpreciopieza = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        TFid = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        CBprecios = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Lfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("AUMENTO DE PRECIO DE PIEZAS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        Ttodos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Ttodos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "TRABAJO", "DESCRIPCIÓN", "PRECIO PIEZAS", "ESTADO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(Ttodos);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 470, 180));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Ingrese ID del Trabajo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        Bañadirpreciopieza.setBackground(new java.awt.Color(0, 255, 0));
        Bañadirpreciopieza.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Bañadirpreciopieza.setText("Añadir");
        Bañadirpreciopieza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BañadirpreciopiezaActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ID", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        TFid.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TFid, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(TFid)
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Precio de Piezas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        CBprecios.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CBprecios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10000", "50000", "100000" }));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("$");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CBprecios, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CBprecios)
                    .addComponent(jLabel2))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(Bañadirpreciopieza)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Bañadirpreciopieza)
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 420, 180));

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 440, 140, 40));
        jPanel1.add(Lfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BañadirpreciopiezaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BañadirpreciopiezaActionPerformed
        // TODO add your handling code here:
        boolean valid=false;
        int pos=0;

        //buscamos el id
        if(TFid.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Debe ingresar una ID", "ERROR", JOptionPane.WARNING_MESSAGE);
        }else{
            for (int i = 0; i < registro.reparaciones.size(); i++) {
                if(registro.reparaciones.get(i).getEstado()==false){
                    if(registro.reparaciones.get(i).getId().equalsIgnoreCase(TFid.getText())){
                        valid=true;
                        pos=i;
                    }
                }
            }

            //validamos si lo encontró
            if(valid){
                if(registro.reparaciones.get(pos).getEstado()==false){
                    //agragamos precio de la pieza
                    if(CBprecios.getSelectedItem().equals("10000")){
                        registro.reparaciones.get(pos).setPreciomaterial(10000);
                    }else if(CBprecios.getSelectedItem().equals("50000")){
                        registro.reparaciones.get(pos).setPreciomaterial(50000);
                    }else if(CBprecios.getSelectedItem().equals("100000")){
                        registro.reparaciones.get(pos).setPreciomaterial(100000);
                    }
                    JOptionPane.showMessageDialog(this, "Precio de material sumado con exito a trabajo con ID: "+registro.reparaciones.get(pos).getId());
                }else{
                    JOptionPane.showMessageDialog(this, "Este trabajo ya está finalizado");
                }

                //Actualizamos la tabla
                DefaultTableModel modelo = (DefaultTableModel) Ttodos.getModel();
                modelo.getDataVector().clear();
                //creamos filas en la table si hay trabajos en proceso
                for (int k = 0; k < registro.reparaciones.size(); k++) {
                    if(registro.reparaciones.get(k).getEstado()==false){
                        modelo.addRow(new Object[]{"", "", "", "", ""});
                    }
                }
                vc=0;
                for (int i = 0; i < registro.reparaciones.size(); i++) {
                    if(registro.reparaciones.get(i).getEstado()==false){
                        Ttodos.setValueAt(registro.reparaciones.get(i).getId(), vc, 0);
                        Ttodos.setValueAt(registro.reparaciones.get(i).getTipotrabajo(), vc, 1);
                        Ttodos.setValueAt(registro.reparaciones.get(i).getDescripcion(), vc, 2);
                        Ttodos.setValueAt(registro.reparaciones.get(i).getPreciomaterial(), vc, 3);
                        if(registro.reparaciones.get(i).getEstado()==false){
                            Ttodos.setValueAt("En proceso", vc, 4);
                        }else{
                            Ttodos.setValueAt("Finalizado", vc, 4);
                        }
                        vc++;
                    }
                }

            }else{
                JOptionPane.showMessageDialog(this, "ID no encontrada");
            }
        }
    }//GEN-LAST:event_BañadirpreciopiezaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(respuestos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(respuestos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(respuestos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(respuestos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new respuestos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bañadirpreciopieza;
    private javax.swing.JComboBox<String> CBprecios;
    private javax.swing.JLabel Lfondo;
    private javax.swing.JTextField TFid;
    private javax.swing.JTable Ttodos;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
